services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    volumes:
      - './frontend:/opt/app'
    restart: always
     
  backend:
    build:
      context: ./backend
    ports:
      - "5050:4000"
    volumes:
      - './backend:/opt/app'
    restart: always