
# This is the teams CD/CD pipeline
name: CI/CD
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# The jobs that is part of the workflow
jobs:
  # Job for testing the frontend and backend code changes
  test:
    # running on ubuntu
    runs-on: ubuntu-latest
    steps:
      # Fetch the code using the checkout action
      - name: Fetch Code
        uses: actions/checkout@v3
      # Installing a Node LTS version
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      # Installing the node modules for the frontend
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install
      # Running the tests for the frontend code
      - name: Run Frontend Tests
        working-directory: ./frontend
        # this command needs to be added to the frontend package.json
        run: npm run test:ci
      # Installing the node modules for the backend
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install
      # Running the linter and tests for the backend code
      - name: Run Backend Tests
        working-directory: ./backend
        run: npm run lint && npm run test